spring:
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  # 指定dev(开发)/pro(生产)环境配置
  profiles:
    active: pro

  messages:
    basename: i18n/messages




# 游客评论头像
comment.avatar: /images/avatar.png


